### ISSUE TITLE
Feature request - multiple gateway's on nic

### ISSUE THREAD

**Issue by ObiRAM** [KurtisLiggett/Simple-IP-Config#66] opened 2018-04-20 13:41 UTC
It would be awsome if i could specify multiple gw's and metrics per gw on the interfaces.

**Comment by quarky42** [comment] 2020-01-22 00:12
I would also like to be able to specify multiple gateways or even multiple IP Addresses (with subnet) on a single profile.

There is a case where I need to have 2 IPs on the same network interface at the same time.

**Comment by quarky42** [comment] 2020-01-22 00:38
I'd like to be able to specify multiple IP addresses on a single NIC.   There is a configuration where I have 2 separate IPs on a NIC and would like to be able to load that as a profile.  I think this is similar to being able to have multiple gateways on a NIC.

How much trouble is it to add the ability to read the second IP from the profiles.ini file and have it set it within the OS?   I suspect adding it to the GUI and making it setable could be somewhat complicated, but even if I could just manually edit the ini file and have it handle 2 IP addresses on the profile and apply it to whatever NIC I select, that would be great.

**Comment by KurtisLiggett** [comment] 2022-03-30 20:06
Closing due to duplicate of issue #8.

**Closed by KurtisLiggett** 2022-03-30 20:06 UTC
Labels: new feature
