### ISSUE TITLE
Problem opening two times the app

### ISSUE THREAD

**Issue by giacomocerquone** [KurtisLiggett/Simple-IP-Config#13] opened 2017-07-02 09:47 UTC
I'm on windows 10 and if I open the app two times, the second time a msgbox show up with this error:

`0x00000101`

Now this is a big problem, especially considering #4 because this morning I started coding the cli part but, **unless we want to create a separate exe** to apply config for desktop link, we need to find a way to execute multiple instances for Simple-Ip

**Comment by KurtisLiggett** [comment] 2017-07-02 19:02
It is by design that you can only run a single instance of the app (in case someone doesn't realize they have it minimized to tray). However, you shouldn't be getting an error. What is supposed to happen is when you try to run a 2nd instance, a tray message pops up alerting you that the program is already running. I've found the problem though... it was a msgbox I was testing and forgot about!

In main.au3, this section
```AutoIt
Func _NewInstance($hWnd, $iMsg, $iwParam, $ilParam)
	MsgBox(0,"",$iwParam)
	if $iwParam == 101 Then
		TrayTip("", "Simple IP Config is already running", 1)
	EndIf
EndFunc
```

should be changed to this
```AutoIt
Func _NewInstance($hWnd, $iMsg, $iwParam, $ilParam)
	if $iwParam == "0x00000101" Then
		TrayTip("", "Simple IP Config is already running", 1)
	EndIf
EndFunc
```

For now, I'm marking this as a bug and will continue the desktop links  discussion in Issue #4 .

**Closed** 2017-07-21 17:08 UTC
Labels: bug, confirmed, fixed
