### ISSUE TITLE
Error  when launching programm on win 7 ""COM error Error number 80020009""

### ISSUE THREAD

**Issue by Nina2007** [KurtisLiggett/Simple-IP-Config#71] opened 2018-08-04 14:51 UTC
![simpliperror](https://user-images.githubusercontent.com/42094369/43677657-f8cf38d6-9805-11e8-97ab-b7abd206467b.PNG)

**Comment by controlzone** [comment] 2018-08-22 22:26
I just got the same error after months of use with no problem. Version 2.9.0.4
Immediately prior to getting the error, I was trying some settings to see if I could start with windows and minimise to tray. I hit the close X thinking that would drop it to the tray but it closed the program (fair enough) but when opening it again, it came back with the COM Error a few times and then the AutoIt Error.
Backing up the profile.ini and then uninstalling + re-installing seems to fix the problem and keeps the profiles.

**Comment by KurtisLiggett** [comment] 2018-08-24 03:34
Bug confirmed. This will happen when trying to check for updates with no internet connection.
Looks like I took some error checking out while testing something.

Temporary fix: open the profiles.ini file and change this line:

`AutoUpdate=true`

to this

`AutoUpdate=false`

**Comment by dajo** [comment] 2018-09-01 18:03
can confirm occurrence, and can confirm fix. Thanks!

**Comment by KurtisLiggett** [comment] 2018-09-22 18:16
This issue has been fixed with [v2.9.1](https://github.com/KurtisLiggett/Simple-IP-Config/releases/tag/2.9.1).

**Closed by KurtisLiggett** 2018-09-22 18:16 UTC
Labels: bug, confirmed
