### ISSUE TITLE
Feature missing - multiple IP addresses on a single NIC / profile

### ISSUE THREAD

**Issue by LaryTech** [KurtisLiggett/Simple-IP-Config#101] opened 2021-08-11 13:22 UTC
Hi great job,

I use Version: 2.9.3 /Win10.
I want to be able  to save in profile,multiple IP addresses on a single NIC
At my job I have 1 network Adapter with 2 ip.

  Later edit 
I see Later and I wil test your sugestion:
https://github.com/KurtisLiggett/Simple-IP-Config/issues/8
Is good to know
  The ini file will store addresses like this
IpAddress=192.168.1.1|10.225.251.12
IpSubnet=255.255.255.0|255.255.255.0

**Comment by LaryTech** [comment] 2021-08-11 15:04
option to restore ( apply ) 
 profile with multiple IP addresses (on a single NIC) 
--not working  on Windows [Version 10.0.19041.985]
in vers 2.8  / 2.9.2/ 2.9.3

**Comment by KurtisLiggett** [comment] 2022-03-30 20:20
Duplicate of #8

**Closed by KurtisLiggett** 2022-03-30 20:20 UTC
