### ISSUE TITLE
Add multiple IP addresses to a single adapter

### ISSUE THREAD

**Issue by raym0nde** [KurtisLiggett/Simple-IP-Config#58] opened 2017-11-30 12:06 UTC
I have an application that requires two IP addresses on a single adapter. It would be great if SIC had the ability to set multiple IPs.

![image](https://user-images.githubusercontent.com/24615894/33429990-ddb8b99a-d59c-11e7-9d15-c81059bce09a.png)

**Comment by KurtisLiggett** [comment] 2018-02-14 21:18
Duplicate of issue #8.
Moved to [Multiple IP Addresses per Profile](https://github.com/KurtisLiggett/Simple-IP-Config/issues/8#issuecomment-365747292)

**Closed by KurtisLiggett** 2018-02-14 21:18 UTC
